### ISSUE TITLE
distance sensor not returning on full salt bucket

### ISSUE THREAD

**Issue by RobertJansen1** [fonske/clack-reader#3]
https://github.com/fonske/clack-reader/blob/ef707730c9346d9353fc0120c4584f2ffb2c7785/esphome/distance-sensor2.h#L62

i have a relatively small salt bucket which can barely hold 25 kg of salt. after i filled it completely for the first time, the distance censor is not returning a value, instead ony a log file.

on my setup i changed this line to:
                            publish_state(0);
now it returns again, and the dashboard is working completely :)

**Comment by fonske** [comment]
@RobertJansen1 
Thanks, i have changed it to your suggestion.
